// src/app/layout.jsx
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; // Your existing global CSS

// IMPORTANT: For Font Awesome icons using <i> tags (like fas fa-plus),
// you need to install @fortawesome/fontawesome-free and import its CSS.
// First, run: npm install @fortawesome/fontawesome-free
// Then, import the CSS here. This provides the icon definitions and font files.
import "@fortawesome/fontawesome-free/css/all.css";

import { Providers } from "../components/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
